#development:
#  adapter: async
#
#test:
#  adapter: async
#
#production:
#  adapter: redis
#  url: redis://localhost:6379/1

production: &production
  adapter: redis
  url: redis://localhost:6379/1
development: &development
  adapter: async
  url: redis://localhost:6379
test: *development