#development:
#  adapter: async
#
#test:
#  adapter: async
#
#production:
#  adapter: redis
#  url: redis://localhost:6379/1

production: &production
  adapter: redis
  url: redis://redistogo:c2d001b173f176043777889d4bba5a12@sculpin.redistogo.com:10803/
development: &development
  adapter: async
  url: redis://localhost:6379
test: *development